// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfwykyshtpfqrxvdiktz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmd3lreXNodHBmcXJ4dmRpa3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzUzMTgsImV4cCI6MjA2OTUxMTMxOH0.sCIRP2qt57jAx1-8Ag0mWzB046fSyCXu6Q3VAXFKLZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});